/**
 * VIA Outlets — Stub Seed Data
 *
 * Transforms the raw API stub JSON into flat RxDB documents ready for bulk
 * insertion. Each export maps 1-to-1 with a collection defined in the schemas.
 *
 * Usage:
 *   import { seedDatabase } from './seeds';
 *   await seedDatabase(db);        // seeds all collections
 *
 *   // or selectively:
 *   import { OUTLET_SEEDS } from './seeds';
 *   await db.outlets.bulkInsert(OUTLET_SEEDS);
 */

import type { ViaOutletsDatabase } from "@/db";
import type {
  AuthSessionDocument,
  CustomerDocument,
  EventDocument,
  OutletDocument,
  ParkingSessionDocument,
  PromotionDocument,
  ServiceDocument,
  StoreDocument,
  TransactionDocument,
  VoucherDocument,
} from "@/schemas";

// ─────────────────────────────────────────────
// Outlets  (from azure_middleware.outlet_list)
// ─────────────────────────────────────────────

export const OUTLET_SEEDS: OutletDocument[] = [
  {
    outlet_id: "mall_001",
    slug: "hede-fashion-outlet-gothenburg",
    name: "Hede Fashion Outlet",
    operator_brand: "VIA Outlets",
    status: "open",
    type: "fashion_outlet",
    country: "SE",
    currency: "SEK",
    hero_image_url:
      "https://cdn.bynder.com/viaoutlets/outlets/mall_001/hero.jpg",
    thumbnail_url:
      "https://cdn.bynder.com/viaoutlets/outlets/mall_001/thumb.jpg",
    location: {
      address: "Hedevägen 5, Kungsbacka",
      city: "Gothenburg",
      postcode: "434 39",
      country: "SE",
      latitude: 57.4645,
      longitude: 12.0165,
    },
    contact: {
      phone: "+46300123456",
      email: "info@hedefashionoutlet.com",
      website: "https://www.hedefashionoutlet.com",
    },
    opening_hours: {
      monday: { open: "10:00", close: "19:00" },
      tuesday: { open: "10:00", close: "19:00" },
      wednesday: { open: "10:00", close: "19:00" },
      thursday: { open: "10:00", close: "19:00" },
      friday: { open: "10:00", close: "20:00" },
      saturday: { open: "10:00", close: "18:00" },
      sunday: { open: "11:00", close: "17:00" },
    },
    stats: {
      total_stores: 75,
      total_gla_sqm: 19000,
      parking_capacity: 1200,
      annual_visitors: 2500000,
    },
    features: [
      "free_parking",
      "restaurant",
      "kids_play_area",
      "accessible",
      "ev_charging",
    ],
    transport: {
      train:
        "Kungsbacka Station (5 min walk) — direct from Gothenburg Central (20 min)",
      bus: "Route 760 from Gothenburg",
    },
    loyalty_earn_rate: "0.5 pts per SEK",
    loyalty_multiplier: 1.0,
    current_offers_count: 8,
  },
  {
    outlet_id: "mall_002",
    slug: "batavia-stad-amsterdam",
    name: "Batavia Stad Fashion Outlet",
    operator_brand: "VIA Outlets",
    status: "open",
    type: "fashion_outlet",
    country: "NL",
    currency: "EUR",
    hero_image_url:
      "https://cdn.bynder.com/viaoutlets/outlets/mall_002/hero.jpg",
    thumbnail_url:
      "https://cdn.bynder.com/viaoutlets/outlets/mall_002/thumb.jpg",
    location: {
      address: "Stadskanaal 101, Lelystad",
      city: "Amsterdam (Lelystad)",
      postcode: "8243 PB",
      country: "NL",
      latitude: 52.4972,
      longitude: 5.4745,
    },
    contact: {
      phone: "+31320123456",
      email: "info@bataviastad.nl",
      website: "https://www.bataviastad.nl",
    },
    opening_hours: {
      monday: { open: "10:00", close: "18:00" },
      tuesday: { open: "10:00", close: "18:00" },
      wednesday: { open: "10:00", close: "18:00" },
      thursday: { open: "10:00", close: "21:00" },
      friday: { open: "10:00", close: "21:00" },
      saturday: { open: "10:00", close: "18:00" },
      sunday: { open: "12:00", close: "18:00" },
    },
    stats: {
      total_stores: 150,
      total_gla_sqm: 42000,
      parking_capacity: 2800,
      annual_visitors: 7000000,
    },
    features: [
      "free_parking",
      "restaurants",
      "kids_play_area",
      "vip_lounge",
      "accessible",
      "ev_charging",
      "tax_refund",
    ],
    transport: {
      bus: "Shuttle bus from Amsterdam Centraal (direct service)",
      car: "30 min from Amsterdam via A6",
    },
    loyalty_earn_rate: "0.5 pts per EUR",
    loyalty_multiplier: 1.0,
    current_offers_count: 21,
  },
  {
    outlet_id: "mall_003",
    slug: "sevilla-fashion-outlet",
    name: "Sevilla Fashion Outlet",
    operator_brand: "VIA Outlets",
    status: "open",
    type: "fashion_outlet",
    country: "ES",
    currency: "EUR",
    hero_image_url:
      "https://cdn.bynder.com/viaoutlets/outlets/mall_003/hero.jpg",
    thumbnail_url:
      "https://cdn.bynder.com/viaoutlets/outlets/mall_003/thumb.jpg",
    location: {
      address: "Carretera Isla Mayor, km 1, Dos Hermanas",
      city: "Sevilla",
      postcode: "41703",
      country: "ES",
      latitude: 37.297,
      longitude: -5.921,
    },
    contact: {
      phone: "+34954123456",
      email: "info@sevillafashionoutlet.com",
      website: "https://www.sevillafashionoutlet.com",
    },
    opening_hours: {
      monday: { open: "10:00", close: "21:00" },
      tuesday: { open: "10:00", close: "21:00" },
      wednesday: { open: "10:00", close: "21:00" },
      thursday: { open: "10:00", close: "21:00" },
      friday: { open: "10:00", close: "22:00" },
      saturday: { open: "10:00", close: "22:00" },
      sunday: { open: "11:00", close: "21:00" },
    },
    stats: {
      total_stores: 120,
      total_gla_sqm: 35000,
      parking_capacity: 2500,
      annual_visitors: 5500000,
    },
    features: [
      "free_parking",
      "restaurants",
      "food_court",
      "kids_play_area",
      "accessible",
      "ev_charging",
      "tax_refund",
    ],
    transport: {
      car: "15 min from Sevilla city centre via SE-30",
      bus: "Route M-135 from Sevilla Prado de San Sebastián",
    },
    loyalty_earn_rate: "0.5 pts per EUR",
    loyalty_multiplier: 1.0,
    current_offers_count: 15,
  },
  {
    outlet_id: "mall_004",
    slug: "zweibrucken-fashion-outlet",
    name: "Zweibrücken Fashion Outlet",
    operator_brand: "VIA Outlets",
    status: "open",
    type: "fashion_outlet",
    country: "DE",
    currency: "EUR",
    hero_image_url:
      "https://cdn.bynder.com/viaoutlets/outlets/mall_004/hero.jpg",
    thumbnail_url:
      "https://cdn.bynder.com/viaoutlets/outlets/mall_004/thumb.jpg",
    location: {
      address: "Londoner Bogen 8, Zweibrücken",
      city: "Zweibrücken",
      postcode: "66482",
      country: "DE",
      latitude: 49.2535,
      longitude: 7.365,
    },
    contact: {
      phone: "+4963327123456",
      email: "info@zweibrueckenfashionoutlet.com",
      website: "https://www.zweibrueckenfashionoutlet.com",
    },
    opening_hours: {
      monday: { open: "10:00", close: "20:00" },
      tuesday: { open: "10:00", close: "20:00" },
      wednesday: { open: "10:00", close: "20:00" },
      thursday: { open: "10:00", close: "20:00" },
      friday: { open: "10:00", close: "20:00" },
      saturday: { open: "10:00", close: "20:00" },
      sunday: {
        open: "closed",
        close: "closed",
        note: "Closed — German Ladenschlussgesetz",
      },
    },
    stats: {
      total_stores: 110,
      total_gla_sqm: 30000,
      parking_capacity: 2000,
      annual_visitors: 4200000,
    },
    features: [
      "free_parking",
      "restaurant",
      "accessible",
      "ev_charging",
      "tax_refund",
      "currency_exchange",
    ],
    transport: {
      car: "1h from Frankfurt, 30 min from Saarbrücken via A8/A6",
      bus: "Regional buses from Kaiserslautern and Saarbrücken",
    },
    loyalty_earn_rate: "0.5 pts per EUR",
    loyalty_multiplier: 1.0,
    current_offers_count: 11,
    regional_note:
      "Outlet closed on Sundays per German federal retail law (Ladenschlussgesetz).",
  },
  {
    outlet_id: "mall_005",
    slug: "scala-milano-outlet",
    name: "Scala Milano Outlet & More",
    operator_brand: "VIA Outlets",
    status: "open",
    type: "fashion_outlet",
    country: "IT",
    currency: "EUR",
    hero_image_url:
      "https://cdn.bynder.com/viaoutlets/outlets/mall_005/hero.jpg",
    thumbnail_url:
      "https://cdn.bynder.com/viaoutlets/outlets/mall_005/thumb.jpg",
    location: {
      address: "Via dell'Outlet 1, Settimo Torinese",
      city: "Milan (Greater)",
      postcode: "10036",
      country: "IT",
      latitude: 45.137,
      longitude: 7.773,
    },
    contact: {
      phone: "+390114123456",
      email: "info@scalamilano.com",
      website: "https://www.scalamilano.com",
    },
    opening_hours: {
      monday: { open: "10:00", close: "20:00" },
      tuesday: { open: "10:00", close: "20:00" },
      wednesday: { open: "10:00", close: "20:00" },
      thursday: { open: "10:00", close: "20:00" },
      friday: { open: "10:00", close: "21:00" },
      saturday: { open: "10:00", close: "21:00" },
      sunday: { open: "10:00", close: "20:00" },
    },
    stats: {
      total_stores: 140,
      total_gla_sqm: 38000,
      parking_capacity: 3000,
      annual_visitors: 6000000,
    },
    features: [
      "free_parking",
      "restaurants",
      "vip_platinum_lounge",
      "personal_shopper",
      "accessible",
      "ev_charging",
      "tax_refund",
      "currency_exchange",
    ],
    transport: {
      train: "Settimo Torinese station (10 min walk)",
      car: "20 min from Turin, 100 min from Milan via A4/A5",
    },
    loyalty_earn_rate: "0.5 pts per EUR",
    loyalty_multiplier: 1.0,
    current_offers_count: 28,
  },
];

// ─────────────────────────────────────────────
// Customers  (4 personas)
// ─────────────────────────────────────────────

export const CUSTOMER_SEEDS: CustomerDocument[] = [
  {
    customer_id: "cust_sophie_001",
    external_id: "EXT-FR-SOPHIE-001",
    program_id: "prog_viacard_001",
    status: "active",
    created_at: "2023-09-14T11:00:00Z",
    last_activity: "2026-06-18T15:30:00Z",
    profile: {
      first_name: "Sophie",
      last_name: "Marchand",
      email: "sophie.marchand@gmail.com",
      mobile: "+33612345678",
      date_of_birth: "1990-07-19",
      gender: "female",
      nationality: "FR",
      country_of_residence: "NL",
      preferred_language: "fr",
      preferred_outlet_id: "mall_002",
      avatar_url:
        "https://cdn.bynder.com/viaoutlets/avatars/cust_sophie_001.jpg",
    },
    address: {
      line1: "Herengracht 284",
      city: "Amsterdam",
      postcode: "1016 BX",
      country: "NL",
    },
    gdpr_consent: {
      marketing_email: true,
      marketing_sms: true,
      marketing_push: true,
      profiling_analytics: true,
      third_party_sharing: false,
      data_processing_basis: "consent",
      accepted_at: "2023-09-14T11:00:00Z",
      last_updated: "2025-01-10T09:00:00Z",
      consent_version: "v3.2-NL",
    },
    loyalty: {
      card_number: "VIA-NL-001-0000001",
      digital_card_url:
        "https://cdn.bynder.com/viacard/digital/cust_sophie_001.pkpass",
      tier: "gold",
      tier_achieved_date: "2025-01-01",
      tier_review_date: "2026-12-31",
      points_balance: 8640,
      lifetime_points: 31200,
      pending_points: 180,
      expiring_points: { amount: 900, expiry_date: "2026-09-30" },
      next_tier: "platinum",
      spend_to_next_tier_eur: 1850.0,
      tier_progress_pct: 63,
      tier_spend_ytd_eur: 3150.0,
      tier_spend_threshold_eur: 5000.0,
    },
    spending_summary: {
      total_spend_ytd_eur: 3150.0,
      total_spend_lifetime_eur: 14800.0,
      visit_count_ytd: 11,
      avg_basket_eur: 286.36,
      last_visit_date: "2026-06-18",
      last_visit_outlet_id: "mall_002",
      favourite_category: "fashion_luxury",
    },
    linked_accounts: {
      apple_wallet: true,
      google_wallet: false,
      social_login: { provider: "google", linked_at: "2023-09-14T11:00:00Z" },
    },
  },
  {
    customer_id: "cust_adam_002",
    external_id: "EXT-GB-ADAM-002",
    program_id: "prog_viacard_001",
    status: "active",
    created_at: "2024-04-05T09:30:00Z",
    last_activity: "2026-05-31T13:00:00Z",
    profile: {
      first_name: "Adam",
      last_name: "Clarke",
      email: "adam.clarke@outlook.com",
      mobile: "+447812345678",
      date_of_birth: "1983-11-02",
      gender: "male",
      nationality: "GB",
      country_of_residence: "DE",
      preferred_language: "en",
      preferred_outlet_id: "mall_004",
    },
    address: {
      line1: "Römerstraße 12",
      city: "Frankfurt am Main",
      postcode: "60311",
      country: "DE",
    },
    gdpr_consent: {
      marketing_email: true,
      marketing_sms: false,
      marketing_push: true,
      profiling_analytics: true,
      third_party_sharing: false,
      data_processing_basis: "consent",
      accepted_at: "2024-04-05T09:30:00Z",
      consent_version: "v3.2-DE",
    },
    loyalty: {
      card_number: "VIA-DE-002-0000001",
      digital_card_url:
        "https://cdn.bynder.com/viacard/digital/cust_adam_002.pkpass",
      tier: "silver",
      tier_achieved_date: "2024-10-01",
      tier_review_date: "2026-12-31",
      points_balance: 3210,
      lifetime_points: 9400,
      pending_points: 0,
      expiring_points: { amount: 400, expiry_date: "2026-09-30" },
      next_tier: "gold",
      spend_to_next_tier_eur: 1290.0,
      tier_progress_pct: 36,
      tier_spend_ytd_eur: 710.0,
      tier_spend_threshold_eur: 2000.0,
    },
    spending_summary: {
      total_spend_ytd_eur: 710.0,
      total_spend_lifetime_eur: 4200.0,
      visit_count_ytd: 4,
      avg_basket_eur: 177.5,
      last_visit_date: "2026-05-31",
      last_visit_outlet_id: "mall_004",
      favourite_category: "sportswear",
    },
    linked_accounts: {
      apple_wallet: false,
      google_wallet: true,
      social_login: null,
    },
  },
  {
    customer_id: "cust_elena_003",
    external_id: "EXT-IT-ELENA-003",
    program_id: "prog_viacard_001",
    status: "active",
    created_at: "2022-03-20T08:00:00Z",
    last_activity: "2026-06-22T17:00:00Z",
    profile: {
      first_name: "Elena",
      last_name: "Ferretti",
      email: "elena.ferretti@libero.it",
      mobile: "+393381234567",
      date_of_birth: "1978-05-25",
      gender: "female",
      nationality: "IT",
      country_of_residence: "IT",
      preferred_language: "it",
      preferred_outlet_id: "mall_005",
    },
    address: {
      line1: "Via Brera 18",
      city: "Milan",
      postcode: "20121",
      country: "IT",
    },
    gdpr_consent: {
      marketing_email: true,
      marketing_sms: true,
      marketing_push: true,
      profiling_analytics: true,
      third_party_sharing: false,
      data_processing_basis: "consent",
      accepted_at: "2022-03-20T08:00:00Z",
      last_updated: "2026-01-05T10:00:00Z",
      consent_version: "v3.2-IT",
    },
    loyalty: {
      card_number: "VIA-IT-003-0000001",
      digital_card_url:
        "https://cdn.bynder.com/viacard/digital/cust_elena_003.pkpass",
      tier: "platinum",
      tier_achieved_date: "2024-01-01",
      tier_review_date: "2026-12-31",
      points_balance: 22400,
      lifetime_points: 89500,
      pending_points: 520,
      expiring_points: { amount: 0, expiry_date: null },
      next_tier: "platinum",
      spend_to_next_tier_eur: null,
      tier_progress_pct: 100,
      tier_spend_ytd_eur: 9800.0,
      tier_spend_threshold_eur: 8000.0,
    },
    spending_summary: {
      total_spend_ytd_eur: 9800.0,
      total_spend_lifetime_eur: 68500.0,
      visit_count_ytd: 22,
      avg_basket_eur: 445.45,
      last_visit_date: "2026-06-22",
      last_visit_outlet_id: "mall_005",
      favourite_category: "fashion_luxury",
    },
    linked_accounts: {
      apple_wallet: true,
      google_wallet: false,
      social_login: { provider: "apple", linked_at: "2022-03-20T08:00:00Z" },
    },
    platinum_benefits: {
      personal_shopper: true,
      vip_lounge_access: true,
      free_valet: true,
      exclusive_preview_events: true,
    },
  },
  {
    customer_id: "cust_marco_004",
    external_id: "EXT-ES-MARCO-004",
    program_id: "prog_viacard_001",
    status: "active",
    created_at: "2026-06-24T10:15:00Z",
    last_activity: "2026-06-24T10:15:00Z",
    profile: {
      first_name: "Marco",
      last_name: "Delgado",
      email: "marco.delgado@hotmail.es",
      mobile: "+34617234567",
      date_of_birth: "1985-03-08",
      gender: "male",
      nationality: "ES",
      country_of_residence: "ES",
      preferred_language: "es",
      preferred_outlet_id: "mall_003",
    },
    address: {
      line1: "Calle Sierpes 40",
      city: "Sevilla",
      postcode: "41004",
      country: "ES",
    },
    gdpr_consent: {
      marketing_email: true,
      marketing_sms: false,
      marketing_push: true,
      profiling_analytics: true,
      third_party_sharing: false,
      data_processing_basis: "consent",
      accepted_at: "2026-06-24T10:15:00Z",
      consent_version: "v3.2-ES",
    },
    loyalty: {
      card_number: "VIA-ES-004-0000001",
      digital_card_url:
        "https://cdn.bynder.com/viacard/digital/cust_marco_004.pkpass",
      tier: "member",
      points_balance: 250,
      lifetime_points: 250,
      pending_points: 0,
      next_tier: "silver",
      spend_to_next_tier_eur: 500.0,
      tier_progress_pct: 0,
      tier_spend_ytd_eur: 0.0,
      tier_spend_threshold_eur: 500.0,
    },
    spending_summary: {
      total_spend_ytd_eur: 0.0,
      total_spend_lifetime_eur: 0.0,
      visit_count_ytd: 0,
      avg_basket_eur: 0.0,
      last_visit_date: null,
      last_visit_outlet_id: null,
      favourite_category: null,
    },
    linked_accounts: {
      apple_wallet: false,
      google_wallet: false,
      social_login: null,
    },
  },
];

// ─────────────────────────────────────────────
// Auth Sessions  (stub / dev tokens only)
// ─────────────────────────────────────────────

export const AUTH_SESSION_SEEDS: AuthSessionDocument[] = [
  {
    session_id: "sess_sophie_001_dev",
    customer_id: "cust_sophie_001",
    access_token: "eyJhbGciOiJSUzI1NiJ9.sophie.dev.token",
    refresh_token: "rt_sophie_3e8a1d2f4b5c6g7h_dev",
    token_type: "Bearer",
    expires_at: "2026-12-31T23:59:59Z", // long expiry for dev only
    scope: "customer:read customer:write loyalty:read",
    program_id: "prog_viacard_001",
  },
  {
    session_id: "sess_adam_002_dev",
    customer_id: "cust_adam_002",
    access_token: "eyJhbGciOiJSUzI1NiJ9.adam.dev.token",
    refresh_token: "rt_adam_7c2b9e1f3a4d5g6h_dev",
    token_type: "Bearer",
    expires_at: "2026-12-31T23:59:59Z",
    scope: "customer:read customer:write loyalty:read",
    program_id: "prog_viacard_001",
  },
  {
    session_id: "sess_elena_003_dev",
    customer_id: "cust_elena_003",
    access_token: "eyJhbGciOiJSUzI1NiJ9.elena.dev.token",
    refresh_token: "rt_elena_1a2b3c4d5e6f7g8h_dev",
    token_type: "Bearer",
    expires_at: "2026-12-31T23:59:59Z",
    scope: "customer:read customer:write loyalty:read",
    program_id: "prog_viacard_001",
  },
  {
    session_id: "sess_marco_004_dev",
    customer_id: "cust_marco_004",
    access_token: "eyJhbGciOiJSUzI1NiJ9.marco.dev.token",
    refresh_token: "rt_marco_7f8g9h0i1j2k3l4m_dev",
    token_type: "Bearer",
    expires_at: "2026-12-31T23:59:59Z",
    scope: "customer:read customer:write loyalty:read",
    program_id: "prog_viacard_001",
  },
];

// ─────────────────────────────────────────────
// Stores (selected brands across outlets)
// ─────────────────────────────────────────────

export const STORE_SEEDS: StoreDocument[] = [
  // Batavia Stad
  {
    store_id: "store_bst_0001",
    outlet_id: "mall_002",
    brand_id: "brand_ralph_lauren",
    name: "Ralph Lauren",
    category: "fashion",
    sub_category: "premium",
    logo_url: "https://cdn.bynder.com/viaoutlets/brands/ralph-lauren/logo.svg",
    hero_image_url:
      "https://cdn.bynder.com/viaoutlets/brands/ralph-lauren/hero.jpg",
    unit_number: "A-12",
    location_description: "Block A, near main entrance",
    status: "open",
    discount_range: "30–70% off RRP",
    accepts_loyalty: true,
    loyalty_multiplier: 2.0,
    tags: ["women", "men", "kids", "lifestyle"],
    rating: 4.5,
    review_count: 312,
  },
  {
    store_id: "store_bst_0002",
    outlet_id: "mall_002",
    brand_id: "brand_calvin_klein",
    name: "Calvin Klein",
    category: "fashion",
    sub_category: "premium",
    logo_url: "https://cdn.bynder.com/viaoutlets/brands/calvin-klein/logo.svg",
    unit_number: "A-18",
    location_description: "Block A",
    status: "open",
    discount_range: "30–60% off RRP",
    accepts_loyalty: true,
    loyalty_multiplier: 1.0,
    tags: ["women", "men", "denim", "underwear"],
    rating: 4.3,
    review_count: 204,
  },
  {
    store_id: "store_bst_0003",
    outlet_id: "mall_002",
    brand_id: "brand_tommy_hilfiger",
    name: "Tommy Hilfiger",
    category: "fashion",
    sub_category: "premium",
    logo_url:
      "https://cdn.bynder.com/viaoutlets/brands/tommy-hilfiger/logo.svg",
    unit_number: "B-04",
    location_description: "Block B",
    status: "open",
    discount_range: "30–70% off RRP",
    accepts_loyalty: true,
    loyalty_multiplier: 1.0,
    rating: 4.2,
    review_count: 287,
  },
  {
    store_id: "store_bst_0004",
    outlet_id: "mall_002",
    brand_id: "brand_adidas",
    name: "Adidas",
    category: "sportswear",
    sub_category: "sports_performance",
    logo_url: "https://cdn.bynder.com/viaoutlets/brands/adidas/logo.svg",
    unit_number: "C-02",
    location_description: "Block C — Sports Street",
    status: "open",
    discount_range: "30–50% off RRP",
    accepts_loyalty: true,
    loyalty_multiplier: 1.5,
    tags: ["footwear", "sportswear", "men", "women", "kids"],
    rating: 4.6,
    review_count: 518,
  },
  {
    store_id: "store_bst_0005",
    outlet_id: "mall_002",
    brand_id: "brand_michael_kors",
    name: "Michael Kors",
    category: "fashion",
    sub_category: "accessories_luxury",
    logo_url: "https://cdn.bynder.com/viaoutlets/brands/michael-kors/logo.svg",
    unit_number: "A-06",
    location_description: "Block A — Luxury Lane",
    status: "open",
    discount_range: "40–60% off RRP",
    accepts_loyalty: true,
    loyalty_multiplier: 3.0,
    tags: ["handbags", "watches", "women", "accessories"],
    rating: 4.7,
    review_count: 429,
  },
  {
    store_id: "store_bst_0006",
    outlet_id: "mall_002",
    brand_id: "brand_nike",
    name: "Nike",
    category: "sportswear",
    logo_url: "https://cdn.bynder.com/viaoutlets/brands/nike/logo.svg",
    unit_number: "C-05",
    location_description: "Block C — Sports Street",
    status: "open",
    discount_range: "25–50% off RRP",
    accepts_loyalty: true,
    loyalty_multiplier: 1.5,
    rating: 4.5,
    review_count: 643,
  },
  // Scala Milano
  {
    store_id: "store_scala_0001",
    outlet_id: "mall_005",
    brand_id: "brand_armani",
    name: "Giorgio Armani Outlet",
    category: "fashion",
    sub_category: "luxury",
    logo_url: "https://cdn.bynder.com/viaoutlets/brands/armani/logo.svg",
    unit_number: "LUX-01",
    location_description: "Luxury Quarter",
    status: "open",
    discount_range: "30–50% off RRP",
    accepts_loyalty: true,
    loyalty_multiplier: 5.0,
    rating: 4.8,
    review_count: 194,
  },
  {
    store_id: "store_scala_0002",
    outlet_id: "mall_005",
    brand_id: "brand_prada",
    name: "Prada",
    category: "fashion",
    sub_category: "luxury",
    logo_url: "https://cdn.bynder.com/viaoutlets/brands/prada/logo.svg",
    unit_number: "LUX-02",
    location_description: "Luxury Quarter",
    status: "open",
    discount_range: "25–45% off RRP",
    accepts_loyalty: true,
    loyalty_multiplier: 5.0,
    rating: 4.9,
    review_count: 276,
  },
  {
    store_id: "store_scala_0003",
    outlet_id: "mall_005",
    brand_id: "brand_max_mara",
    name: "Max Mara",
    category: "fashion",
    sub_category: "premium",
    logo_url: "https://cdn.bynder.com/viaoutlets/brands/max-mara/logo.svg",
    unit_number: "B-07",
    location_description: "Block B",
    status: "open",
    discount_range: "35–60% off RRP",
    accepts_loyalty: true,
    loyalty_multiplier: 3.0,
    rating: 4.7,
    review_count: 148,
  },
  {
    store_id: "store_scala_0004",
    outlet_id: "mall_005",
    brand_id: "brand_tods",
    name: "Tod's",
    category: "fashion",
    sub_category: "luxury_footwear",
    logo_url: "https://cdn.bynder.com/viaoutlets/brands/tods/logo.svg",
    unit_number: "LUX-08",
    location_description: "Luxury Quarter",
    status: "open",
    discount_range: "30–50% off RRP",
    accepts_loyalty: true,
    loyalty_multiplier: 5.0,
    rating: 4.8,
    review_count: 113,
  },
];

// ─────────────────────────────────────────────
// Services (flattened from nested stub object)
// ─────────────────────────────────────────────

export const SERVICE_SEEDS: ServiceDocument[] = [
  // Batavia Stad — Restrooms
  {
    service_id: "svc_bst_wc_001",
    outlet_id: "mall_002",
    type: "restroom",
    name: "Toilets — Visitor Centre",
    location_description: "Main Entrance Block A",
    features: ["baby_changing", "accessible", "family_room"],
    status: "operational",
    metadata: { cleanliness_rating: 4.5 },
  },
  {
    service_id: "svc_bst_wc_002",
    outlet_id: "mall_002",
    type: "restroom",
    name: "Toilets — Block C (Sports Street)",
    location_description: "Between Nike and Adidas, Block C",
    features: ["baby_changing", "accessible"],
    status: "operational",
    metadata: { cleanliness_rating: 4.2 },
  },
  {
    service_id: "svc_bst_wc_003",
    outlet_id: "mall_002",
    type: "restroom",
    name: "Toilets — Restaurant Terrace",
    location_description: "Adjacent to La Place restaurant, Block D",
    features: ["accessible"],
    status: "operational",
    metadata: { cleanliness_rating: 4.3 },
  },
  // Batavia Stad — Rest Areas
  {
    service_id: "svc_bst_ra_001",
    outlet_id: "mall_002",
    type: "rest_area",
    name: "Central Square Seating",
    location_description: "Open-air seating, Central Square",
    features: ["outdoor", "accessible"],
    status: "operational",
    metadata: { seating_capacity: 60 },
  },
  {
    service_id: "svc_bst_ra_002",
    outlet_id: "mall_002",
    type: "vip_lounge",
    name: "VIA Card Gold & Platinum Lounge",
    location_description: "Visitor Centre, upper floor",
    features: ["wifi", "refreshments", "concierge_desk", "luggage_storage"],
    status: "operational",
    access_required: "loyalty_gold_plus",
    opening_hours: { open: "10:00", close: "18:00" },
    metadata: { seating_capacity: 25 },
  },
  {
    service_id: "svc_bst_ra_003",
    outlet_id: "mall_002",
    type: "kids_area",
    name: "Kids Play Corner",
    location_description: "Block B, near Tommy Hilfiger",
    features: ["soft_play", "supervised_weekends"],
    status: "operational",
    metadata: { seating_capacity: 20 },
  },
  // Batavia Stad — Info / Tax / EV
  {
    service_id: "svc_bst_info_001",
    outlet_id: "mall_002",
    type: "visitor_centre",
    name: "Visitor Centre & VIA Card Desk",
    location_description: "Main Entrance — Block A",
    features: [],
    status: "operational",
    opening_hours: { open: "10:00", close: "18:00" },
    metadata: {
      services: [
        "wayfinding",
        "via_card_signup",
        "lost_found",
        "wheelchair_hire",
        "tax_refund_assistance",
      ],
      languages: ["nl", "en", "de", "fr"],
    },
  },
  {
    service_id: "svc_bst_taxfree_001",
    outlet_id: "mall_002",
    type: "tax_refund",
    name: "Tax Refund Desk — Global Blue",
    location_description: "Visitor Centre, ground floor",
    features: [],
    status: "operational",
    opening_hours: { open: "10:00", close: "17:30" },
    metadata: {
      provider: "Global Blue",
      min_spend_eur: 50.0,
      eligible: "Non-EU residents only",
    },
  },
  {
    service_id: "svc_bst_ev_001",
    outlet_id: "mall_002",
    type: "ev_charging",
    name: "EV Charging — Car Park North",
    location_description: "Car Park North, Row N1–N3",
    features: ["Type2", "CCS"],
    status: "operational",
    metadata: { charger_count: 8, chargers_available: 5, operator: "Fastned" },
  },
  // Zweibrücken services
  {
    service_id: "svc_zw_wc_001",
    outlet_id: "mall_004",
    type: "restroom",
    name: "WC — Gallery A",
    location_description: "Gallery A, near entrance",
    features: ["baby_changing", "accessible"],
    status: "operational",
    metadata: { cleanliness_rating: 4.4 },
  },
  {
    service_id: "svc_zw_wc_002",
    outlet_id: "mall_004",
    type: "restroom",
    name: "WC — Food Court",
    location_description: "Adjacent to food court",
    features: ["accessible"],
    status: "operational",
    metadata: { cleanliness_rating: 4.1 },
  },
  {
    service_id: "svc_zw_ra_001",
    outlet_id: "mall_004",
    type: "rest_area",
    name: "Central Seating Atrium",
    location_description: "Central Gallery Junction",
    features: ["covered", "accessible"],
    status: "operational",
    metadata: { seating_capacity: 45 },
  },
  {
    service_id: "svc_zw_ra_002",
    outlet_id: "mall_004",
    type: "vip_lounge",
    name: "VIA Card Silver+ Lounge",
    location_description: "Information Centre, upper level",
    features: ["wifi", "refreshments"],
    status: "operational",
    access_required: "loyalty_silver_plus",
    metadata: { seating_capacity: 15 },
  },
  {
    service_id: "svc_zw_fx_001",
    outlet_id: "mall_004",
    type: "currency_exchange",
    name: "Wechselstube / Change",
    location_description: "Information Centre",
    features: [],
    status: "operational",
    metadata: {
      provider: "Eurochange",
      currencies: ["EUR", "GBP", "USD", "CHF", "SEK", "PLN"],
    },
  },
  {
    service_id: "svc_zw_ev_001",
    outlet_id: "mall_004",
    type: "ev_charging",
    name: "EV Charging — Car Park B",
    location_description: "Car Park B",
    features: ["Type2", "CCS"],
    status: "operational",
    metadata: {
      charger_count: 6,
      chargers_available: 4,
      operator: "EnBW mobility+",
    },
  },
  // Scala Milano — Platinum lounge
  {
    service_id: "svc_scala_vip_001",
    outlet_id: "mall_005",
    type: "vip_lounge",
    name: "Platinum VIP Lounge — Scala Milano",
    location_description: "First floor, main building",
    features: ["wifi", "refreshments", "personal_shopper", "cloakroom"],
    status: "operational",
    access_required: "loyalty_platinum",
    metadata: { seating_capacity: 40 },
  },
];

// ─────────────────────────────────────────────
// Transactions  (Sophie's history)
// ─────────────────────────────────────────────

export const TRANSACTION_SEEDS: TransactionDocument[] = [
  {
    transaction_id: "txn_soph_001",
    customer_id: "cust_sophie_001",
    type: "earn",
    sub_type: "purchase",
    points: 186,
    spend_amount: 372.0,
    currency: "EUR",
    earn_rate: "0.5 pts/EUR",
    outlet_id: "mall_002",
    outlet_name: "Batavia Stad Fashion Outlet",
    store_id: "store_bst_0001",
    store_name: "Ralph Lauren",
    receipt_number: "RL-20260618-4490",
    transaction_date: "2026-06-18T14:45:00Z",
    status: "confirmed",
    bonus_points: 0,
  },
  {
    transaction_id: "txn_soph_002",
    customer_id: "cust_sophie_001",
    type: "earn",
    sub_type: "bonus_campaign",
    points: 500,
    outlet_id: "mall_002",
    transaction_date: "2026-06-01T09:00:00Z",
    status: "confirmed",
    campaign_id: "camp_via_summer26",
    campaign_name: "VIA Summer Double-Up",
    bonus_points: 500,
  },
  {
    transaction_id: "txn_soph_003",
    customer_id: "cust_sophie_001",
    type: "burn",
    sub_type: "redemption",
    points: -2000,
    redeemed_value_eur: 20.0,
    outlet_id: "mall_002",
    store_id: "store_bst_0003",
    store_name: "Tommy Hilfiger",
    receipt_number: "TH-20260510-0091",
    transaction_date: "2026-05-10T16:20:00Z",
    status: "confirmed",
  },
  {
    transaction_id: "txn_soph_004",
    customer_id: "cust_sophie_001",
    type: "earn",
    sub_type: "purchase",
    points: 310,
    spend_amount: 620.0,
    currency: "EUR",
    outlet_id: "mall_001",
    outlet_name: "Hede Fashion Outlet",
    store_id: "store_hede_0007",
    store_name: "Michael Kors",
    receipt_number: "MK-20260420-2211",
    transaction_date: "2026-04-20T11:10:00Z",
    status: "confirmed",
    multi_outlet_visit: true,
  },
  // Marco's welcome points
  {
    transaction_id: "txn_marco_001",
    customer_id: "cust_marco_004",
    type: "earn",
    sub_type: "welcome",
    points: 250,
    outlet_id: "mall_003",
    transaction_date: "2026-06-24T10:15:00Z",
    status: "confirmed",
    campaign_name: "Welcome Bonus",
    bonus_points: 250,
  },
];

// ─────────────────────────────────────────────
// Vouchers  (Elena's wallet)
// ─────────────────────────────────────────────

export const VOUCHER_SEEDS: VoucherDocument[] = [
  {
    voucher_id: "vchr_elena_001",
    customer_id: "cust_elena_003",
    code: "PLAT-PRESALE-E3K9",
    title: "Platinum Pre-Sale Early Access — 30% Off",
    description:
      "Exclusive early access to the Summer Sale for Platinum VIA Card members.",
    type: "percentage_discount",
    discount_pct: 30,
    applicable_outlets: [
      "mall_001",
      "mall_002",
      "mall_003",
      "mall_004",
      "mall_005",
    ],
    issued_at: "2026-06-20T00:00:00Z",
    valid_from: "2026-06-28T00:00:00Z",
    valid_until: "2026-06-30T23:59:59Z",
    status: "active",
    tier_exclusive: "platinum",
    qr_payload: "VCHR-cust_elena_003-vchr_elena_001-PLAT-PRESALE-E3K9",
    barcode_type: "qr",
  },
  {
    voucher_id: "vchr_elena_002",
    customer_id: "cust_elena_003",
    code: "BDAY-ELENA-2026",
    title: "Birthday Gift — €50 VIA Voucher",
    description:
      "Happy Birthday Elena! A gift from us to celebrate your special day.",
    type: "fixed_amount",
    discount_value: 50.0,
    currency: "EUR",
    applicable_outlets: [
      "mall_001",
      "mall_002",
      "mall_003",
      "mall_004",
      "mall_005",
    ],
    issued_at: "2026-05-20T00:00:00Z",
    valid_from: "2026-05-25T00:00:00Z",
    valid_until: "2026-06-25T23:59:59Z",
    status: "active",
    qr_payload: "VCHR-cust_elena_003-vchr_elena_002-BDAY-ELENA-2026",
    barcode_type: "qr",
  },
  {
    voucher_id: "vchr_elena_003",
    customer_id: "cust_elena_003",
    code: "VIP-LOUNGE-SCALA",
    title: "Scala Milano VIP Lounge Pass",
    description:
      "Complimentary access to the Platinum VIP Lounge at Scala Milano Outlet.",
    type: "access_pass",
    applicable_outlets: ["mall_005"],
    issued_at: "2026-01-01T00:00:00Z",
    valid_from: "2026-01-01T00:00:00Z",
    valid_until: "2026-12-31T23:59:59Z",
    status: "active",
    tier_exclusive: "platinum",
    qr_payload: "VCHR-cust_elena_003-vchr_elena_003-VIP-LOUNGE-SCALA",
    barcode_type: "qr",
    usage_limit: "unlimited",
    usage_count: 14,
  },
  {
    voucher_id: "vchr_elena_004",
    customer_id: "cust_elena_003",
    code: "USED-XMAS-ELENA",
    title: "Christmas Gift Voucher — €30",
    type: "fixed_amount",
    discount_value: 30.0,
    currency: "EUR",
    issued_at: "2025-12-01T00:00:00Z",
    status: "redeemed",
    redeemed_at: "2025-12-22T14:05:00Z",
    redeemed_at_outlet_id: "mall_005",
    redeemed_at_store_id: "store_scala_0019",
  },
];

// ─────────────────────────────────────────────
// Parking Sessions  (Adam at Zweibrücken)
// ─────────────────────────────────────────────

export const PARKING_SESSION_SEEDS: ParkingSessionDocument[] = [
  {
    session_id: "sess_pkbl_ZW9K2M",
    customer_id: "cust_adam_002",
    venue_id: "venue_zw_004",
    zone_id: "zone_zw_main",
    bay_number: "G1-0112",
    license_plate: "F-AC-2024",
    started_at: "2026-06-24T10:00:00Z",
    ended_at: "2026-06-24T14:30:00Z",
    parking_policy: "free_all_day",
    duration_minutes: 270,
    amount_due_eur: 0.0,
    amount_charged_eur: 0.0,
    loyalty_points_earned: 0,
    status: "completed",
    ticket_token: "TKT-sess_pkbl_ZW9K2M-2026",
  },
];

// ─────────────────────────────────────────────
// Promotions  (from Contentstack)
// ─────────────────────────────────────────────

export const PROMOTION_SEEDS: PromotionDocument[] = [
  {
    uid: "blt_via_promo_summer26",
    slug: "summer-sale-2026",
    locale: "en-gb",
    title: "VIA Summer Sale 2026",
    status: "active",
    type: "network_wide",
    headline: "Summer Sale — Up to 70% Off Premium Brands",
    sub_headline:
      "Ralph Lauren, Calvin Klein, Tommy Hilfiger, Adidas, Nike and hundreds more.",
    body_copy:
      "The VIA Summer Sale is back. Shop end-of-season collections from the world's most-loved premium brands at up to 70% off regular retail prices.",
    terms_and_conditions:
      "Discounts on selected lines only. Varies by brand and outlet. While stocks last.",
    hero_image_url:
      "https://cdn.bynder.com/viaoutlets/campaigns/summer-sale-2026/promo-hero-en.jpg",
    gallery: [
      {
        url: "https://cdn.bynder.com/viaoutlets/campaigns/summer-sale-2026/gallery-fashion.jpg",
      },
      {
        url: "https://cdn.bynder.com/viaoutlets/campaigns/summer-sale-2026/gallery-sport.jpg",
      },
    ],
    valid_from: "2026-07-01T00:00:00Z",
    valid_until: "2026-07-31T23:59:59Z",
    applicable_outlets: [
      "mall_001",
      "mall_002",
      "mall_003",
      "mall_004",
      "mall_005",
    ],
    applicable_categories: [
      "fashion_luxury",
      "fashion_premium",
      "sportswear",
      "accessories",
      "beauty",
    ],
    coniq_campaign_id: "camp_via_summer26",
    loyalty_bonus_points: 300,
    available_locales: [
      "en-gb",
      "fr-fr",
      "es-es",
      "it-it",
      "de-de",
      "nl-nl",
      "sv-se",
    ],
    cta: {
      label: "Find Your Nearest Outlet",
      action_type: "deeplink",
      action_value: "outlets/map",
    },
  },
];

// ─────────────────────────────────────────────
// Events  (from Contentstack)
// ─────────────────────────────────────────────

export const EVENT_SEEDS: EventDocument[] = [
  {
    uid: "blt_evt_001",
    slug: "platinum-presale-summer26",
    title: "Platinum Pre-Sale Preview Evening",
    type: "members_event",
    venue_outlet_id: "mall_005",
    venue_outlet_name: "Scala Milano Outlet & More",
    location_in_outlet: "VIP Lounge & Entire Outlet",
    start_datetime: "2026-06-28T18:00:00Z",
    end_datetime: "2026-06-28T22:00:00Z",
    image_url:
      "https://cdn.bynder.com/viaoutlets/events/platinum-presale-milan/card.jpg",
    short_description:
      "Exclusive early evening access to the Summer Sale for Platinum VIA Card members. Champagne reception, personal styling and 30% off.",
    is_free: true,
    registration_required: true,
    capacity: 150,
    spots_remaining: 22,
    target_audience: ["platinum"],
  },
  {
    uid: "blt_evt_002",
    slug: "family-fun-day-bst-july26",
    title: "Family Fun Day — Batavia Stad",
    type: "family_event",
    venue_outlet_id: "mall_002",
    venue_outlet_name: "Batavia Stad Fashion Outlet",
    location_in_outlet: "Central Square & Kids Corner",
    start_datetime: "2026-07-12T11:00:00Z",
    end_datetime: "2026-07-12T16:00:00Z",
    image_url:
      "https://cdn.bynder.com/viaoutlets/events/family-fun-bst/card.jpg",
    short_description:
      "A free family day out with face painting, live music, kids activities and great summer deals across 150 stores.",
    is_free: true,
    registration_required: false,
    target_audience: ["all", "family"],
  },
  {
    uid: "blt_evt_003",
    slug: "flamenco-fashion-sevilla-july26",
    title: "Flamenco & Fashion Night — Sevilla",
    type: "cultural_event",
    venue_outlet_id: "mall_003",
    venue_outlet_name: "Sevilla Fashion Outlet",
    location_in_outlet: "Central Plaza",
    start_datetime: "2026-07-18T20:00:00Z",
    end_datetime: "2026-07-18T23:00:00Z",
    image_url:
      "https://cdn.bynder.com/viaoutlets/events/flamenco-sevilla/card.jpg",
    short_description:
      "An unforgettable evening of live flamenco performance amid the summer sale. Free entry, extended shopping until midnight.",
    is_free: true,
    registration_required: false,
    target_audience: ["all"],
  },
];

// ─────────────────────────────────────────────
// Master seed function
// ─────────────────────────────────────────────

/**
 * Seeds all collections. Uses bulkInsert which skips duplicates if called again
 * (RxDB throws on primaryKey conflicts — use bulkUpsert for idempotent reseeds).
 */
export async function seedDatabase(
  db: ViaOutletsDatabase,
  options: { upsert?: boolean } = {},
): Promise<void> {
  const insert = options.upsert ? "bulkUpsert" : "bulkInsert";

  await Promise.all([
    db.outlets[insert](OUTLET_SEEDS),
    db.customers[insert](CUSTOMER_SEEDS),
    db.auth_sessions[insert](AUTH_SESSION_SEEDS),
    db.stores[insert](STORE_SEEDS),
    db.services[insert](SERVICE_SEEDS),
    db.transactions[insert](TRANSACTION_SEEDS),
    db.vouchers[insert](VOUCHER_SEEDS),
    db.parking_sessions[insert](PARKING_SESSION_SEEDS),
    db.promotions[insert](PROMOTION_SEEDS),
    db.events[insert](EVENT_SEEDS),
  ]);

  console.log("[VIA RxDB] Seed complete — all collections populated.");
}
